services:
  web:
    image: nginx:latest
    container_name: nginx-web-tier
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - custom_bridge_network

  db:
    image: mysql:8.0
    container_name: mysql-data-tier
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: demo
    volumes:
      - mysql8_datavol:/var/lib/mysql
    networks:
      - custom_bridge_network

volumes:
  mysql8_datavol:

networks:
  custom_bridge_network:
    name: nginx_mysql_network
    driver: bridge